In [ ]:
import numpy as np

##Задача 1 Центр масс.

Допишите функцию, которая вычисляет радиус-вектора центра масс трёх точек a, b, c. Все точки заданы радиус-векторами в n-мерном евклидовом пространстве, в виде массивов np.array. Массы точек заданы массивом mass. 

In [ ]:
def centre_mass(a, b, c, mass):
    S=(mass[0]*a+mass[1]*b+mass[2]*c)/(mass[0]+mass[1]+mass[2])
    return S

a = np.array([0, 0, 1])
b = np.array([2, 0, 0])
c = np.array([1, 1, 0])
mass = np.array([1, 1, 2])
print(centre_mass(a,b,c, mass))

[1.   0.5  0.25]


##Задача 2  Поворот на 90 градусов.

Допишите функцию, которая поворачивает двумерный вектор на 90 градусов против часовой стрелки, в предположении, что вектор задан координатами в ортонормированном базисе и вектор с координатами $\left(\begin{array}{c}1\\0\end{array}\right)$ при повороте отображается в $\left(\begin{array}{c}0\\1\end{array}\right)$.

In [ ]:
def rotate90(x):
    '''Повернуть x на 90 градусов против часовой стрелки'''
    x = np.array(x)
    angle = np.pi/2
    rotate_matrix = np.array([ #матрица поворота
        [np.cos(angle), -np.sin(angle)],
        [np.sin(angle), np.cos(angle)]
    ])
    return rotate_matrix@x

In [ ]:
a = np.array([[1, 0]]).T
np.round(rotate90(a), 10)

array([[0.],
       [1.]])

##Задача 3  Минимальное собственное значение.

Рассмотрите диагональную матрицу $D$ размера $n \times n$ и вектор-столбец $u$. Выберите $D$ и $u$ случайным образом (сгенерировав их элементы из стандартного нормального распределения) и найдите минимальное собственное значение и соответствующий собственный ему собственный вектор матрицы
$$
A=D+\frac{u u^{T}}{u^{T} u}
$$

Рассмотрите случай $n=10^{2}$

In [ ]:
n = 100

D = (np.eye(n)*np.random.normal(size=n))
u = np.random.normal(size=n).reshape(-1, 1)
A = D + u@u.T/(u.T@u)

eigvals, eigvectors = np.linalg.eig(A)

# выбор минимального собств. значения и соответствующего ему собств. вектора
mineig, mineig_vector = eigvals[np.argmin(eigvals)], eigvectors[:, np.argmin(eigvals)]
mineig_vector = mineig_vector.reshape(-1, 1)
print('Минимальное собственное значение', mineig)
print('Соответствующий ему собственный вектор:')
print(mineig_vector)

Минимальное собственное значение -2.5194319393987135
Соответствующий ему собственный вектор:
[[-6.89120549e-06]
 [-6.87249622e-07]
 [-1.08965308e-05]
 [ 2.08480857e-07]
 [ 7.86252097e-06]
 [-2.86218879e-05]
 [-1.58610215e-05]
 [ 1.06626131e-05]
 [ 2.91743920e-05]
 [ 1.54144200e-05]
 [-1.22021063e-05]
 [-7.74473907e-06]
 [ 6.50187050e-06]
 [ 7.28520419e-06]
 [-8.42596000e-06]
 [ 1.22820782e-06]
 [-1.09889299e-05]
 [-2.47402129e-05]
 [-2.41906594e-05]
 [-1.98472003e-05]
 [ 8.02537225e-06]
 [ 1.62532557e-05]
 [ 1.56374557e-05]
 [ 1.89618177e-05]
 [-1.98978418e-05]
 [-2.20221141e-05]
 [ 1.16899958e-05]
 [-3.81989769e-06]
 [ 2.13296555e-05]
 [ 4.38990963e-05]
 [ 5.43591975e-05]
 [ 2.46320192e-06]
 [-2.27949942e-05]
 [ 1.60511538e-05]
 [-7.12666708e-05]
 [ 4.21533340e-06]
 [-1.23483622e-05]
 [-9.38906264e-06]
 [-3.02660617e-06]
 [-2.03647309e-05]
 [-9.06430655e-06]
 [ 1.30191420e-05]
 [-1.42274628e-05]
 [-8.18768963e-06]
 [ 4.60930607e-06]
 [ 1.09327650e-05]
 [-7.43797551e-06]
 [ 2.07919376e

##Задача 4  Возмущение корреляционной матрицы.

Управляющий активами Neurozhaika Capital Management noлучил от своих аналитиков корреляционную матрицу трёх фондовых индексов,

$$
\mathbf{C}=\left(\begin{array}{ccc}
1 & 0.9 & 0.7 \\
0.9 & 1 & 0.4 \\
0.7 & 0.4 & 1
\end{array}\right)
$$

Коэффициент корреляции $0.4$ кажется ему завышенным, и он хочет поиграть с этой величиной, промоделировав гипотетический портфель, заменив $0.4$ на $0.3$. Найдите собственнные значения исходной ${\mathbf{C}}_{0} $ и возмущённой $\overline{\mathbf{C}}_{0} $ матриц. Несмотря на относительно малое возмущение и разумный вид возмущённой матрицы какие-то из собственных значений станут отрицательными, и матрица $\overline{\mathbf{C}}_{0}$ не будет положительно определенной, что неприемлемо. Рассмотрите следующий "спектральный" рецепт восстановления свойств корреляционной матрицы:


- Посчитать все собственные значения $\lambda_{i} $  и собственные векторы возмущённой матрицы. Ввести новые собственные значения по правилу $\lambda_{i}^{\prime} = \lambda_{i}$, если $\lambda_{i} \geq 0$, иначе $\lambda_{i}^{\prime}=0$
- Умножить собственные векторы на модифицированные собственные значения $\lambda_{i}^{\prime}$ , и использовать их в качестве столбцов новой матрицы $\mathbf{B}^{\prime}$ .
- Отнормировать строки матрицы $\mathbf{B}^{\prime}$ (векторы) на единичную длину, получив тем самым новую матрицу $\mathbf{B}$.
- Построить новую возмущённую корреляционную матрицу по правилу $\overline{\mathbf{C}}_{1}=\mathbf{B B}^{T}$.

Полученная таким образом матрица $\overline{\mathbf{C}}_{1}$ будет положительно определенной с единицами на главной диагонали, то есть отвечать формальным требованиям, предъявляемым к корреляционной матрице. Найти численно матрицу $\overline{\mathbf{C}}_{1}$.

In [ ]:
С0 = np.array([[1.0, 0.9, 0.7], [0.9, 1.0, 0.4], [0.7, 0.4, 1]]) #исходная матрица
С0_perm = np.array([[1.0, 0.9, 0.7], [0.9, 1.0, 0.3], [0.7, 0.3, 1]]) #исходная матрица
w0, v0 = np.linalg.eig(С0)
w0_perm, v0_perm = np.linalg.eig(С0_perm)
print("Собственные значения невозмущённой матрицы: ", w0)
print("Собственные значения возмущённой матрицы: ", w0_perm)
w1 = np.zeros(3) # 1 шаг
for i in range(3):
  if w0_perm[i] >= 0:
    w1[i] = w0_perm[i]
B1 = v0_perm*w1 #2 шаг
B_norm = (B1**2).sum(axis=1)**(1/2) #3 шаг
B = B1/ B_norm.reshape(-1, 1)
C1 = B@B.T #4 шаг
C1

Собственные значения невозмущённой матрицы:  [2.35363603 0.03034736 0.6160166 ]
Собственные значения возмущённой матрицы:  [ 2.29672779 -0.00735244  0.71062465]


array([[1.        , 0.96153494, 0.87605522],
       [0.96153494, 1.        , 0.70990276],
       [0.87605522, 0.70990276, 1.        ]])

##Задача 5  Вunch-Nielsen-Sorensen formula.

Решите задачу 3 для случая $n=10^{4}$. Для этого используйте  Вunch-Nielsen-Sorensen formula.

Let $\lambda_{i}$ denote the eigenvalues of $A$ and $\tilde{\lambda}_{i}$ denote the eigenvalues of the updated matrix $\tilde{A}=A+v v^{T} .$ In the special case when $A$ is diagonal, the eigenvectors $\tilde{q}_{i}$ of $\tilde{A}$ can be written

$$
\left(\tilde{q}_{i}\right)_{k}=\frac{N_{i} v_{k}}{\lambda_{k}-\tilde{\lambda}_{i}}
$$

where $N_{i}$ is a number that makes the vector $\tilde{q}_{i}$ normalized. 

In [ ]:
def find_eigenvector(D, v, eig): #ищет собственное значение A=D+v@v.T, соответствующее собственному значению A
    """ 
    D: диагональная матрица n x n
    v: вектор размера n x 1
    eig: собственное значение A 
    """
    D_eigs = np.diag(D)
    q = v / (D_eigs.reshape(-1, 1) - eig)
    q /= np.linalg.norm(q)    
    return q

In [ ]:
n = 10000 #1 способ

D = (np.eye(n)*np.random.normal(size=n))
u = np.random.normal(size=n).reshape(-1, 1)
A = D + u@u.T/(u.T@u)

eigvals = np.linalg.eigvals(A)
mineig = eigvals.min()
mineig_vector = find_eigenvector(D, u, mineig)

print('Минимальное собственное значение', mineig)
print('Соответствующий ему собственный вектор:')
print(mineig_vector)

Минимальное собственное значение -4.125965895258424
Соответствующий ему собственный вектор:
[[-4.83505105e-06]
 [ 3.07771475e-05]
 [-4.28828480e-05]
 ...
 [ 1.64925772e-05]
 [-4.25097032e-05]
 [-8.47102203e-05]]


In [ ]:
def find_mineig(A): #2 способ

    iters = 20000
    v0 = np.zeros((A.shape[0], 1))
    v0[0,0] = 1
    v = v0
    max_eig = np.zeros(iters)
    const = 100
    for i in range(iters):
        v = v/np.max(np.abs(v))
        new_v = (A-const*np.eye(A.shape[0]))@v

        max_eig[i] = new_v.T@v/(v.T@v)
        v = new_v
    return max_eig[-1]+const

In [ ]:
n = 10000

D = (np.eye(n)*np.random.normal(size=n))
u = np.random.normal(size=n).reshape(-1, 1)
A = D + u@u.T/(u.T@u)

# eigvals = np.linalg.eigvals(A)
# mineig = eigvals.min()
mineig = find_mineig(A)
mineig_vector = find_eigenvector(D, u, mineig)

print('Минимальное собственное значение', mineig)
print('Соответствующий ему собственный вектор:')
print(mineig_vector)